# https://docs.github.com/ja/github/administering-a-repository/configuration-options-for-dependency-updates#
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  assignees:
  - terakoya76
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  assignees:
    - terakoya76
