name: test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        go: ["1.18", "1.19", "1.20"]

    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v4
      id: cache-go-sum
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: download dependencies
      if: steps.cache-go-sum.outputs.cache-hit != 'true'
      run: go mod download

    - name: lint
      run: make lint

    - name: test
      run: go test -race -v -coverprofile coverage.out -covermode atomic ./...

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1
      with:
        infile: coverage.out
        outfile: coverage.lcov
      if: "matrix.go == 1.20"

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
      if: "matrix.go == 1.20"

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: [build]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
