name: test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        go: ["1.18", "1.19", "1.20"]

    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v3
      id: cache-go-sum
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: download dependencies
      if: steps.cache-go-sum.outputs.cache-hit != 'true'
      run: go mod download

    - name: lint
      run: make lint

    - name: test
      run: go test -race -v -coverprofile coverage.out -covermode atomic ./...

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1
      with:
        infile: coverage.out
        outfile: coverage.lcov
      if: "matrix.go == 1.20"

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
      if: "matrix.go == 1.20"
